resources.base.path = src/main/resources
adk.agent.model = gemini-2.5-flash
adk.agent.config.path = /agents
spring.main.allow-bean-definition-overriding=true

tool.maps = tool.maps.agent
tool.search = tool.search.agent
tool.code = tool.code.execution

traveler.root = traveler.root.agent
traveler.dining = traveler.dining.agent
traveler.flight = traveler.flight.agent
traveler.activity = traveler.activity.agent
traveler.itinerary = traveler.itinerary.agent
traveler.accommodation = traveler.accommodation.agent

report.root = report.root.writer
report.topic = report.topic.researcher
report.content = report.content.analyst
report.research = report.research.coordinator

code.root = code.root.agent
code.generator = code.generator.agent
code.converter = code.converter.agent
code.critic = code.critic.agent
code.refactor = code.refactor.agent
code.bundler = code.bundler.agent
code.review = code.review.agent
code.refiner = code.refiner.agent

blogger.root = blogger.root.agent
blogger.aggregator = blogger.aggregator.agent
blogger.writer = blogger.writer.agent
blogger.editor = blogger.editor.agent
blogger.formatter = blogger.formatter.agent
blogger.health = blogger.health.researcher
blogger.finance = blogger.finance.researcher
blogger.tech = blogger.tech.researcher

tutor.root = tutor.root.agent
tutor.code = tutor.code.agent
tutor.math = tutor.math.agent
tutor.science = tutor.science.agent
